/**
 * Builds the dashboard's tokens stylesheet from the one token source,
 * design/tokens/cawco.tokens.json (W3C DTCG). Every visual value the
 * dashboard uses is defined there; app.css only imports the result.
 *
 * A token's `$value` is its light (or only) value. `$extensions["dev.cawco"]`
 * carries the scheme and media variants:
 *   dark     the dark value; the token is emitted as light-dark(light, dark)
 *   coarse   the value under (pointer: coarse)
 *   compact  the value under (pointer: coarse), (width < 640px)
 * References (`{group.name}`) are emitted as `var(--name)`, so the cascade
 * keeps resolving them at runtime under the active colour scheme.
 *
 * The same build emits the Apple app's tokens into CawCoKit's CawCoDesign
 * module: a colour asset catalog and Tokens.swift (build-tokens-apple.ts).
 *
 *   bun run tokens
 */
import StyleDictionary from "style-dictionary";
import type { Dictionary, TransformedToken } from "style-dictionary/types";
import { colourSetsAction, swiftFormat } from "./build-tokens-apple";
import { isProductToken } from "./token-groups";

const SOURCE = "../../design/tokens/cawco.tokens.json";
const OUT_DIR = "src/lib/tokens/";
const OUT_FILE = "tokens.css";
const APPLE_DIR = "../apple/Packages/CawCoKit/Sources/CawCoDesign/";
/** The decision-page skill CawCo ships (packages/hub/src/bundled-skills.ts): its pages wear the same tokens. */
const SKILL_DIR = "../../packages/hub/skills/decision-page/";
const EXT = "dev.cawco";

const MEDIA = {
  coarse: "(pointer: coarse)",
  compact: "(pointer: coarse), (width < 640px)",
} as const;

interface Variants {
  coarse?: string;
  compact?: string;
  dark?: string;
}

function cssValue(raw: string, names: Set<string>, where: string): string {
  return raw.replace(/\{([^}]+)\}/g, (_, ref: string) => {
    const name = ref.split(".").at(-1) ?? ref;
    if (!names.has(name)) {
      throw new Error(`${where}: unknown reference {${ref}}`);
    }
    return `var(--${name})`;
  });
}

/** The authored variants: Style Dictionary resolves references inside
    `$extensions` too, and a resolved value would freeze the light scheme. */
function variantsOf(token: TransformedToken): Variants {
  return (token.original.$extensions?.[EXT] ?? {}) as Variants;
}

function declaration(token: TransformedToken, names: Set<string>): string {
  const light = cssValue(String(token.original.$value), names, token.name);
  const { dark } = variantsOf(token);
  if (dark === undefined) {
    return `    --${token.name}: ${light};`;
  }
  return `    --${token.name}: light-dark(${light}, ${cssValue(dark, names, token.name)});`;
}

function format({ dictionary }: { dictionary: Dictionary }): string {
  const tokens = dictionary.allTokens.filter(isProductToken);
  const names = new Set(tokens.map((t) => t.name));
  const lines = [
    "/* Generated by `bun run tokens` from design/tokens/cawco.tokens.json.",
    "   Do not edit: change the token source and rebuild. */",
    "@layer theme {",
    "  :root {",
  ];
  for (const token of tokens) {
    if (token.$description) {
      lines.push(`    /* ${token.$description} */`);
    }
    lines.push(declaration(token, names));
  }
  lines.push("  }");
  for (const [key, query] of Object.entries(MEDIA) as [
    keyof typeof MEDIA,
    string,
  ][]) {
    const scoped = tokens.filter((t) => variantsOf(t)[key] !== undefined);
    if (scoped.length === 0) {
      continue;
    }
    lines.push("", `  @media ${query} {`, "    :root {");
    for (const token of scoped) {
      const value = cssValue(String(variantsOf(token)[key]), names, token.name);
      lines.push(`      --${token.name}: ${value};`);
    }
    lines.push("    }", "  }");
  }
  lines.push("}", "");
  return lines.join("\n");
}

const sd = new StyleDictionary({
  source: [SOURCE],
  usesDtcg: true,
  log: { verbosity: "verbose", warnings: "error" },
  hooks: {
    transforms: {
      "name/css-leaf": {
        type: "name",
        transform: (token: TransformedToken) => token.path.at(-1) ?? token.name,
      },
    },
    formats: { "css/cawco-theme": format, "swift/cawco-tokens": swiftFormat },
    actions: { "apple/cawco-colorsets": colourSetsAction },
  },
  platforms: {
    css: {
      transforms: ["name/css-leaf"],
      buildPath: OUT_DIR,
      files: [{ destination: OUT_FILE, format: "css/cawco-theme" }],
    },
    skill: {
      transforms: ["name/css-leaf"],
      buildPath: SKILL_DIR,
      files: [{ destination: "kit/tokens.css", format: "css/cawco-theme" }],
    },
    apple: {
      transforms: ["name/css-leaf"],
      buildPath: APPLE_DIR,
      files: [
        { destination: "Generated/Tokens.swift", format: "swift/cawco-tokens" },
      ],
      actions: ["apple/cawco-colorsets"],
    },
  },
});

await sd.buildAllPlatforms();
