/**
 * Writes the native app's copy of the tool presentation rules
 * (src/tool-presentation.ts) as Swift: the vocabulary as enums, every kind as
 * data. The app's interpreter (CawCoTranscript/ToolDescriptor.swift) reads it.
 *
 *   bun scripts/tool-presentation.ts          write the file
 *   bun scripts/tool-presentation.ts --check  fail when the file is stale
 *
 * Both fail when a kind names a glyph or ink either client cannot draw, and
 * when the rules' code changed on one client and not the other.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  FACTS,
  LINE_CAP,
  MCP_NAME,
  type Piece,
  PRIMARY_FIELDS,
  PRIMARY_MAX,
  PROSE_FIELD,
  REFUSAL_TAGS,
  RENDERERS,
  RESULT_CAP,
  type Sentence,
  STATUSES,
  TOOL_KINDS,
  TRANSFORMS,
  type Variant,
} from "../src/tool-presentation.ts";

const OUT = join(
  import.meta.dir,
  "../../../apps/apple/Packages/CawCoKit/Sources/CawCoTranscript/Generated/ToolPresentation.swift"
);

/** `path-leaf-span` → `pathLeafSpan`. */
const KEBAB = /-([a-z])/g;
const caseName = (name: string): string =>
  name.replace(KEBAB, (_, letter: string) => letter.toUpperCase());

const str = (text: string): string =>
  `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const raw = (text: string): string => `#"${text}"#`;
const opt = <T>(value: T | undefined, write: (value: T) => string): string =>
  value === undefined ? "nil" : write(value);
const list = <T>(values: T[], write: (value: T) => string): string =>
  `[${values.map(write).join(", ")}]`;

function enumOf(name: string, cases: string[]): string {
  const lines = cases.map((value) => {
    const swift = caseName(value);
    return swift === value
      ? `        case ${swift}`
      : `        case ${swift} = ${str(value)}`;
  });
  return `    enum ${name}: String, Sendable {\n${lines.join("\n")}\n    }`;
}

function piece(p: Piece): string {
  return `Piece(from: ${list(p.from, str)}, cut: ${opt(p.as, (as) => `.${caseName(as)}`)}, text: ${opt(p.text, str)}, unless: ${opt(p.unless, str)}, wrap: ${opt(p.wrap, (w) => `(${str(w[0])}, ${str(w[1])})`)}, orShortest: ${p.orShortest === true})`;
}

const pieces = (value: Piece | Piece[] | undefined): string => {
  if (value === undefined) {
    return "[]";
  }
  return list(Array.isArray(value) ? value : [value], piece);
};

function label(rule: Sentence["label"]): string {
  if (rule === undefined) {
    return "nil";
  }
  if (rule === "tool-name") {
    return ".toolName";
  }
  if (typeof rule === "string") {
    return `.words(${str(rule)})`;
  }
  if ("template" in rule) {
    return `.slot(template: ${str(rule.template)}, slot: ${piece(rule.slot)}, fallback: ${str(rule.fallback)})`;
  }
  return `.field(${piece(rule.from)})`;
}

function sentence(s: Sentence, indent: string): string {
  const fields = [
    `label: ${label(s.label)}`,
    `object: ${pieces(s.object)}`,
    `objectMono: ${s.objectMono ?? true}`,
    `detail: ${pieces(s.detail)}`,
    `detailMono: ${s.detailMono ?? false}`,
    `chip: ${opt(s.chip, (c) => `Chip(field: ${str(c.field)}, text: ${str(c.text)})`)}`,
    `fact: ${opt(s.fact, (f) => `.${caseName(f)}`)}`,
    `factDiff: ${s.factDiff ?? false}`,
    `favicon: ${opt(s.favicon, piece)}`,
    `secondLine: ${s.secondLine ?? false}`,
  ];
  return `Sentence(\n${fields.map((f) => `${indent}    ${f}`).join(",\n")}\n${indent})`;
}

function variant(v: Variant, indent: string): string {
  const when = `When(action: ${opt(v.when.action, str)}, names: ${opt(v.when.names, (n) => list(n, str))}, patch: ${opt(v.when.patch, String)}, status: ${opt(v.when.status, (s) => `.${s}`)})`;
  return `Variant(\n${indent}    when: ${when},\n${indent}    renderer: ${opt(v.renderer, (r) => `.${r}`)},\n${indent}    sentence: ${sentence(v.sentence, `${indent}    `)}\n${indent})`;
}

function generate(): string {
  const kinds = TOOL_KINDS.map((kind) => {
    const i = "            ";
    return [
      "        Kind(",
      `${i}id: .${caseName(kind.id)},`,
      `${i}names: ${list(kind.names, str)},`,
      `${i}namePattern: ${opt(kind.namePattern, raw)},`,
      `${i}glyph: ${str(kind.glyph)},`,
      `${i}ink: ${str(kind.ink)},`,
      `${i}one: ${str(kind.one)},`,
      `${i}many: ${str(kind.many)},`,
      `${i}renderer: .${kind.renderer},`,
      `${i}sentence: ${sentence(kind.sentence, i)},`,
      `${i}variants: ${list(kind.variants ?? [], (v) => variant(v, i))}`,
      "        ),",
    ].join("\n");
  });
  return `// Generated by \`bun run tools\` (packages/core) from packages/core/src/tool-presentation.ts.
// Do not edit: change that file and run it again. \`bun run tools:check\` fails while this is stale.
// Interpreters: ts ${pair.ts} swift ${pair.swift}

import Foundation

/// How a tool call is presented in a transcript, as data: the rules the
/// dashboard reads from packages/core, here for the native interpreter
/// (ToolDescriptor) and renderers (ToolViews).
nonisolated enum ToolPresentation {
${enumOf("Renderer", RENDERERS)}

${enumOf("Transform", TRANSFORMS)}

${enumOf("Fact", FACTS)}

${enumOf("Status", STATUSES)}

${enumOf(
  "KindID",
  TOOL_KINDS.map((kind) => kind.id)
)}

    /// A piece of the sentence: the first of \`from\` that is a non-blank string, cut by \`cut\`.
    struct Piece: Sendable {
        let from: [String]
        let cut: Transform?
        let text: String?
        let unless: String?
        let wrap: (String, String)?
        let orShortest: Bool
    }

    enum Label: Sendable {
        case words(String)
        case slot(template: String, slot: Piece, fallback: String)
        case field(Piece)
        case toolName
    }

    struct Chip: Sendable {
        let field: String
        let text: String
    }

    struct Sentence: Sendable {
        let label: Label?
        let object: [Piece]
        let objectMono: Bool
        let detail: [Piece]
        let detailMono: Bool
        let chip: Chip?
        let fact: Fact?
        let factDiff: Bool
        let favicon: Piece?
        let secondLine: Bool
    }

    struct When: Sendable {
        let action: String?
        let names: [String]?
        let patch: Bool?
        let status: Status?
    }

    struct Variant: Sendable {
        let when: When
        let renderer: Renderer?
        let sentence: Sentence
    }

    struct Kind: Sendable {
        let id: KindID
        let names: [String]
        let namePattern: String?
        let glyph: String
        let ink: String
        let one: String
        let many: String
        let renderer: Renderer
        let sentence: Sentence
        let variants: [Variant]
    }

    static let lineCap = ${LINE_CAP}
    static let resultCap = ${RESULT_CAP}
    static let primaryMax = ${PRIMARY_MAX}
    static let primaryFields: [String] = ${list(PRIMARY_FIELDS, str)}
    static let refusalTags = ${raw(REFUSAL_TAGS)}
    static let mcpName = ${raw(MCP_NAME)}
    static let proseField = ${str(PROSE_FIELD)}

    static let kinds: [Kind] = [
${kinds.join("\n")}
    ]
}
`;
}

/**
 * Every glyph and ink a kind names, drawn by both clients: a name either
 * client lacks would turn its rows generic (or, for an ink on iOS, stop the
 * app), so it fails here instead.
 */
function missingOnClients(): string[] {
  const repo = join(import.meta.dir, "../../..");
  const design = join(repo, "apps/apple/Packages/CawCoKit/Sources/CawCoDesign");
  const web = readFileSync(
    join(
      repo,
      "apps/dashboard/src/lib/components/features/tool-cards/descriptors.ts"
    ),
    "utf8"
  );
  const keysOf = (table: string): Set<string> => {
    const body = web.match(
      new RegExp(`const ${table}: Record<string, \\w+> = \\{([^}]*)\\}`)
    )?.[1];
    if (body === undefined) {
      throw new Error(`tools:check: descriptors.ts has no ${table} table`);
    }
    return new Set([...body.matchAll(/"([^"]+)":/g)].map((m) => m[1] ?? ""));
  };
  const webGlyphs = keysOf("GLYPHS");
  const webInks = keysOf("INKS");
  const swiftGlyphs = new Set(
    [
      ...readFileSync(join(design, "Glyph.swift"), "utf8").matchAll(
        /case \w+ = "([^"]+)"/g
      ),
    ].map((m) => m[1] ?? "")
  );
  const swiftInk = (ink: string): boolean =>
    existsSync(join(design, "Resources/Tokens.xcassets", `${ink}.colorset`));
  const missing: string[] = [];
  for (const kind of TOOL_KINDS) {
    if (!webGlyphs.has(kind.glyph)) {
      missing.push(`${kind.id}: glyph ${kind.glyph} not in the web's GLYPHS`);
    }
    if (!swiftGlyphs.has(kind.glyph)) {
      missing.push(`${kind.id}: glyph ${kind.glyph} not in iOS Glyph.swift`);
    }
    if (!webInks.has(kind.ink)) {
      missing.push(`${kind.id}: ink ${kind.ink} not in the web's INKS`);
    }
    if (!swiftInk(kind.ink)) {
      missing.push(`${kind.id}: ink ${kind.ink} has no iOS colour set`);
    }
  }
  return missing;
}

/**
 * The rules as code, not data: how both clients read the kinds (the sentence,
 * the field order, the JSON form, the facts). The data is generated, so it
 * cannot drift; this code is written twice, in src/tool-presentation.ts and in
 * the app's ToolDescriptor.swift, and nothing here can run the Swift. So the
 * pair is pinned in the generated file, and a change to one side alone fails:
 * whoever changes how one client reads a call changes the other in the same
 * commit. Comments and whitespace are not the rules and are not counted.
 */
const PIN = /^\/\/ Interpreters: ts ([0-9a-f]{16}) swift ([0-9a-f]{16})$/m;
const BLOCK_COMMENT = /^\s*\/\*[\s\S]*?\*\/\s*$/gm;
const LINE_COMMENT = /^\s*\/\/.*$/gm;
const WHITESPACE = /\s+/g;
const PROSE_FIELD_LINE = /^export const PROSE_FIELD = .*$/m;

function fingerprint(code: string): string {
  const rules = code
    .replace(BLOCK_COMMENT, "")
    .replace(LINE_COMMENT, "")
    .replace(WHITESPACE, " ")
    .trim();
  return new Bun.CryptoHasher("sha256")
    .update(rules)
    .digest("hex")
    .slice(0, 16);
}

function interpreters(): { ts: string; swift: string } {
  const source = readFileSync(
    join(import.meta.dir, "../src/tool-presentation.ts"),
    "utf8"
  );
  // The constants and kinds the generator writes into Swift as data.
  const start = source.indexOf("export const LINE_CAP");
  const kinds = source.indexOf("export const TOOL_KINDS");
  const end = source.indexOf("\n];", kinds);
  if (start < 0 || kinds < 0 || end < 0) {
    throw new Error(
      "tools:check: src/tool-presentation.ts no longer has its data block (LINE_CAP … TOOL_KINDS)"
    );
  }
  const code = (source.slice(0, start) + source.slice(end + 3)).replace(
    PROSE_FIELD_LINE,
    ""
  );
  const swift = readFileSync(join(OUT, "../../ToolDescriptor.swift"), "utf8");
  return { ts: fingerprint(code), swift: fingerprint(swift) };
}

const pair = interpreters();
const pinned = (() => {
  try {
    return readFileSync(OUT, "utf8").match(PIN);
  } catch {
    return null;
  }
})();
if (pinned) {
  const tsMoved = pinned[1] !== pair.ts;
  const swiftMoved = pinned[2] !== pair.swift;
  if (tsMoved !== swiftMoved) {
    const [moved, still] = tsMoved
      ? ["packages/core/src/tool-presentation.ts", "ToolDescriptor.swift"]
      : ["ToolDescriptor.swift", "packages/core/src/tool-presentation.ts"];
    console.error(
      `tools:check: ${moved} changed how a tool call reads and ${still} did not. Make the same change there (the two must read every call the same way), then run \`bun run tools\` in packages/core.`
    );
    process.exit(1);
  }
}

const missing = missingOnClients();
if (missing.length) {
  console.error(
    `tools:check: a kind names what a client cannot draw:\n  ${missing.join("\n  ")}`
  );
  process.exit(1);
}

const swift = generate();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    current = "";
  }
  if (current !== swift) {
    console.error(
      `tools:check: ${OUT} is stale against src/tool-presentation.ts. Run \`bun run tools\` in packages/core.`
    );
    process.exit(1);
  }
  console.log("tools:check: the Swift tool presentation matches packages/core");
} else {
  writeFileSync(OUT, swift);
  console.log(`wrote ${OUT}`);
}
