/**
 * Writes the native app's copy of the tool presentation rules
 * (src/tool-presentation.ts) as Swift: the vocabulary as enums, every kind as
 * data. The app's interpreter (CawCoTranscript/ToolDescriptor.swift) reads it.
 *
 *   bun scripts/tool-presentation.ts          write the file
 *   bun scripts/tool-presentation.ts --check  fail when the file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  FACTS,
  LINE_CAP,
  MCP_NAME,
  type Piece,
  PRIMARY_MAX,
  PROSE_FIELD,
  REFUSAL_TAGS,
  RENDERERS,
  RESULT_CAP,
  type Sentence,
  STATUSES,
  TOOL_KINDS,
  TRANSFORMS,
  type Variant,
} from "../src/tool-presentation.ts";

const OUT = join(
  import.meta.dir,
  "../../../apps/apple/Packages/CawCoKit/Sources/CawCoTranscript/Generated/ToolPresentation.swift"
);

/** `path-leaf-span` → `pathLeafSpan`. */
const KEBAB = /-([a-z])/g;
const caseName = (name: string): string =>
  name.replace(KEBAB, (_, letter: string) => letter.toUpperCase());

const str = (text: string): string =>
  `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const raw = (text: string): string => `#"${text}"#`;
const opt = <T>(value: T | undefined, write: (value: T) => string): string =>
  value === undefined ? "nil" : write(value);
const list = <T>(values: T[], write: (value: T) => string): string =>
  `[${values.map(write).join(", ")}]`;

function enumOf(name: string, cases: string[]): string {
  const lines = cases.map((value) => {
    const swift = caseName(value);
    return swift === value
      ? `        case ${swift}`
      : `        case ${swift} = ${str(value)}`;
  });
  return `    enum ${name}: String, Sendable {\n${lines.join("\n")}\n    }`;
}

function piece(p: Piece): string {
  return `Piece(from: ${list(p.from, str)}, cut: ${opt(p.as, (as) => `.${caseName(as)}`)}, text: ${opt(p.text, str)}, unless: ${opt(p.unless, str)}, wrap: ${opt(p.wrap, (w) => `(${str(w[0])}, ${str(w[1])})`)}, orShortest: ${p.orShortest === true})`;
}

const pieces = (value: Piece | Piece[] | undefined): string => {
  if (value === undefined) {
    return "[]";
  }
  return list(Array.isArray(value) ? value : [value], piece);
};

function label(rule: Sentence["label"]): string {
  if (rule === undefined) {
    return "nil";
  }
  if (rule === "tool-name") {
    return ".toolName";
  }
  if (typeof rule === "string") {
    return `.words(${str(rule)})`;
  }
  if ("template" in rule) {
    return `.slot(template: ${str(rule.template)}, slot: ${piece(rule.slot)}, fallback: ${str(rule.fallback)})`;
  }
  return `.field(${piece(rule.from)})`;
}

function sentence(s: Sentence, indent: string): string {
  const fields = [
    `label: ${label(s.label)}`,
    `object: ${pieces(s.object)}`,
    `objectMono: ${s.objectMono ?? true}`,
    `detail: ${pieces(s.detail)}`,
    `detailMono: ${s.detailMono ?? false}`,
    `chip: ${opt(s.chip, (c) => `Chip(field: ${str(c.field)}, text: ${str(c.text)})`)}`,
    `fact: ${opt(s.fact, (f) => `.${caseName(f)}`)}`,
    `factDiff: ${s.factDiff ?? false}`,
    `favicon: ${opt(s.favicon, piece)}`,
    `secondLine: ${s.secondLine ?? false}`,
  ];
  return `Sentence(\n${fields.map((f) => `${indent}    ${f}`).join(",\n")}\n${indent})`;
}

function variant(v: Variant, indent: string): string {
  const when = `When(action: ${opt(v.when.action, str)}, names: ${opt(v.when.names, (n) => list(n, str))}, patch: ${opt(v.when.patch, String)}, status: ${opt(v.when.status, (s) => `.${s}`)})`;
  return `Variant(\n${indent}    when: ${when},\n${indent}    renderer: ${opt(v.renderer, (r) => `.${r}`)},\n${indent}    sentence: ${sentence(v.sentence, `${indent}    `)}\n${indent})`;
}

function generate(): string {
  const kinds = TOOL_KINDS.map((kind) => {
    const i = "            ";
    return [
      "        Kind(",
      `${i}id: .${caseName(kind.id)},`,
      `${i}names: ${list(kind.names, str)},`,
      `${i}namePattern: ${opt(kind.namePattern, raw)},`,
      `${i}glyph: ${str(kind.glyph)},`,
      `${i}ink: ${str(kind.ink)},`,
      `${i}one: ${str(kind.one)},`,
      `${i}many: ${str(kind.many)},`,
      `${i}renderer: .${kind.renderer},`,
      `${i}sentence: ${sentence(kind.sentence, i)},`,
      `${i}variants: ${list(kind.variants ?? [], (v) => variant(v, i))}`,
      "        ),",
    ].join("\n");
  });
  return `// Generated by \`bun run tools\` (packages/core) from packages/core/src/tool-presentation.ts.
// Do not edit: change that file and run it again. \`bun run tools:check\` fails while this is stale.

import Foundation

/// How a tool call is presented in a transcript, as data: the rules the
/// dashboard reads from packages/core, here for the native interpreter
/// (ToolDescriptor) and renderers (ToolViews).
nonisolated enum ToolPresentation {
${enumOf("Renderer", RENDERERS)}

${enumOf("Transform", TRANSFORMS)}

${enumOf("Fact", FACTS)}

${enumOf("Status", STATUSES)}

${enumOf(
  "KindID",
  TOOL_KINDS.map((kind) => kind.id)
)}

    /// A piece of the sentence: the first of \`from\` that is a non-blank string, cut by \`cut\`.
    struct Piece: Sendable {
        let from: [String]
        let cut: Transform?
        let text: String?
        let unless: String?
        let wrap: (String, String)?
        let orShortest: Bool
    }

    enum Label: Sendable {
        case words(String)
        case slot(template: String, slot: Piece, fallback: String)
        case field(Piece)
        case toolName
    }

    struct Chip: Sendable {
        let field: String
        let text: String
    }

    struct Sentence: Sendable {
        let label: Label?
        let object: [Piece]
        let objectMono: Bool
        let detail: [Piece]
        let detailMono: Bool
        let chip: Chip?
        let fact: Fact?
        let factDiff: Bool
        let favicon: Piece?
        let secondLine: Bool
    }

    struct When: Sendable {
        let action: String?
        let names: [String]?
        let patch: Bool?
        let status: Status?
    }

    struct Variant: Sendable {
        let when: When
        let renderer: Renderer?
        let sentence: Sentence
    }

    struct Kind: Sendable {
        let id: KindID
        let names: [String]
        let namePattern: String?
        let glyph: String
        let ink: String
        let one: String
        let many: String
        let renderer: Renderer
        let sentence: Sentence
        let variants: [Variant]
    }

    static let lineCap = ${LINE_CAP}
    static let resultCap = ${RESULT_CAP}
    static let primaryMax = ${PRIMARY_MAX}
    static let refusalTags = ${raw(REFUSAL_TAGS)}
    static let mcpName = ${raw(MCP_NAME)}
    static let proseField = ${str(PROSE_FIELD)}

    static let kinds: [Kind] = [
${kinds.join("\n")}
    ]
}
`;
}

const swift = generate();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    current = "";
  }
  if (current !== swift) {
    console.error(
      `tools:check: ${OUT} is stale against src/tool-presentation.ts. Run \`bun run tools\` in packages/core.`
    );
    process.exit(1);
  }
  console.log("tools:check: the Swift tool presentation matches packages/core");
} else {
  writeFileSync(OUT, swift);
  console.log(`wrote ${OUT}`);
}
